project:
  type: book
  output-dir: docs
  
book:
  title: "An Overview of LASSO, Ridge, and Elastic Net Regularized Regression Methods"
  author: "Autumn Weeks, Kathleen Annis, Matt Thompson"
  date: "11/4/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - dataset_methods.qmd
    - JacksonHeart.qmd
    - NCI60.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib



format:
  html:
    theme: cerulean
  pdf:
    documentclass: scrreprt
    cite-method: biblatex

editor: visual


